#include <unity.h>

#include "../src/FeatureFlags.h"

void testFeatureFlagsDefaultToIntegratedDiagnostics() {
  TEST_ASSERT_TRUE(BPMWATCH_ENABLE_DISPLAY);
  TEST_ASSERT_TRUE(BPMWATCH_ENABLE_GY511);
  TEST_ASSERT_TRUE(BPMWATCH_ENABLE_COMPASS);
  TEST_ASSERT_TRUE(BPMWATCH_ENABLE_MAX30102);
  TEST_ASSERT_TRUE(BPMWATCH_ENABLE_I2C_SCAN);
  TEST_ASSERT_TRUE(BPMWATCH_ENABLE_SOS);
  TEST_ASSERT_TRUE(BPMWATCH_ENABLE_RADAR_HEADING);
  TEST_ASSERT_EQUAL(50000L, BPMWATCH_MAX30102_FINGER_IR_MIN);
  TEST_ASSERT_EQUAL(70U, BPMWATCH_MAX30102_MIN_SPS);
  TEST_ASSERT_EQUAL(650L, BPMWATCH_MAX30102_MIN_IR_AC);
  TEST_ASSERT_EQUAL(5500UL, BPMWATCH_MAX30102_MIN_IR_AC_RATIO_PPM);
  TEST_ASSERT_EQUAL(500L, BPMWATCH_MAX30102_WRIST_IRAC_THR);
  TEST_ASSERT_EQUAL(350L, BPMWATCH_MAX30102_WRIST_IRAC_EXIT_THR);
  TEST_ASSERT_EQUAL(5500UL, BPMWATCH_MAX30102_WRIST_RATIO_THR_PPM);
  TEST_ASSERT_EQUAL(4500UL, BPMWATCH_MAX30102_WRIST_RATIO_EXIT_PPM);
  TEST_ASSERT_EQUAL(2000U, BPMWATCH_MAX30102_SIGNAL_LOST_HOLD_MS);
  TEST_ASSERT_EQUAL(BPMWATCH_MAX30102_WRIST_IRAC_THR,
                    BPMWATCH_MAX30102_WRIST_MIN_IR_AC);
  TEST_ASSERT_EQUAL(BPMWATCH_MAX30102_WRIST_RATIO_THR_PPM,
                    BPMWATCH_MAX30102_WRIST_MIN_IR_AC_RATIO_PPM);
  TEST_ASSERT_EQUAL(45, BPMWATCH_MAX30102_BPM_MIN);
  TEST_ASSERT_EQUAL(180, BPMWATCH_MAX30102_BPM_MAX);
  TEST_ASSERT_TRUE(BPMWATCH_MAX30102_WRIST_MODE);
  TEST_ASSERT_EQUAL(350U, BPMWATCH_MAX30102_REFRACTORY_MS);
  TEST_ASSERT_EQUAL(400U, BPMWATCH_MAX30102_INTERVAL_MIN_MS);
  TEST_ASSERT_EQUAL(1300U, BPMWATCH_MAX30102_INTERVAL_MAX_MS);
  TEST_ASSERT_EQUAL(45U, BPMWATCH_MAX30102_INTERVAL_JUMP_PERCENT);
  TEST_ASSERT_EQUAL(3U, BPMWATCH_MAX30102_REQUIRED_STABLE_BEATS);
  TEST_ASSERT_TRUE(BPMWATCH_MAX30102_RESET_ON_NO_FINGER);
}
