#pragma once

#ifndef BPMWATCH_ENABLE_DISPLAY
#define BPMWATCH_ENABLE_DISPLAY true
#endif

#ifndef BPMWATCH_ENABLE_GY511
#define BPMWATCH_ENABLE_GY511 true
#endif

#ifndef BPMWATCH_ENABLE_MAX30102
#define BPMWATCH_ENABLE_MAX30102 true
#endif

#ifndef BPMWATCH_ENABLE_I2C_SCAN
#define BPMWATCH_ENABLE_I2C_SCAN true
#endif

#define BPMWATCH_NEEDS_I2C \
  (BPMWATCH_ENABLE_I2C_SCAN || BPMWATCH_ENABLE_GY511 || BPMWATCH_ENABLE_MAX30102)
