#pragma once

#ifndef BPMWATCH_ENABLE_DISPLAY
#define BPMWATCH_ENABLE_DISPLAY true
#endif

#ifndef BPMWATCH_ENABLE_GY511
#define BPMWATCH_ENABLE_GY511 true
#endif

#ifndef BPMWATCH_ENABLE_COMPASS
#define BPMWATCH_ENABLE_COMPASS BPMWATCH_ENABLE_GY511
#endif

#ifndef BPMWATCH_ENABLE_LSM303D
#define BPMWATCH_ENABLE_LSM303D BPMWATCH_ENABLE_COMPASS
#endif

#ifndef BPMWATCH_ENABLE_COMPASS_DIAG
#define BPMWATCH_ENABLE_COMPASS_DIAG BPMWATCH_ENABLE_COMPASS
#endif

#ifndef BPMWATCH_ENABLE_COMPASS_ACC_RAW
#define BPMWATCH_ENABLE_COMPASS_ACC_RAW BPMWATCH_ENABLE_COMPASS
#endif

#ifndef BPMWATCH_ENABLE_TILT_COMPENSATION
#define BPMWATCH_ENABLE_TILT_COMPENSATION false
#endif

#ifndef BPMWATCH_ENABLE_MAX30102
#define BPMWATCH_ENABLE_MAX30102 true
#endif

#ifndef BPMWATCH_MAX30102_FINGER_IR_MIN
#define BPMWATCH_MAX30102_FINGER_IR_MIN 50000L
#endif

#ifndef BPMWATCH_MAX30102_MIN_SPS
#define BPMWATCH_MAX30102_MIN_SPS 70U
#endif

#ifndef BPMWATCH_MAX30102_MIN_IR_AC
#define BPMWATCH_MAX30102_MIN_IR_AC 650L
#endif

#ifndef BPMWATCH_MAX30102_MIN_IR_AC_RATIO_PPM
#define BPMWATCH_MAX30102_MIN_IR_AC_RATIO_PPM 5500UL
#endif

#ifndef BPMWATCH_MAX30102_WRIST_IRAC_THR
#define BPMWATCH_MAX30102_WRIST_IRAC_THR 500L
#endif

#ifndef BPMWATCH_MAX30102_WRIST_IRAC_EXIT_THR
#define BPMWATCH_MAX30102_WRIST_IRAC_EXIT_THR 350L
#endif

#ifndef BPMWATCH_MAX30102_WRIST_RATIO_THR_PPM
#define BPMWATCH_MAX30102_WRIST_RATIO_THR_PPM 5500UL
#endif

#ifndef BPMWATCH_MAX30102_WRIST_RATIO_EXIT_PPM
#define BPMWATCH_MAX30102_WRIST_RATIO_EXIT_PPM 4500UL
#endif

#ifndef BPMWATCH_MAX30102_SIGNAL_LOST_HOLD_MS
#define BPMWATCH_MAX30102_SIGNAL_LOST_HOLD_MS 2000U
#endif

#ifndef BPMWATCH_MAX30102_WRIST_MIN_IR_AC
#define BPMWATCH_MAX30102_WRIST_MIN_IR_AC BPMWATCH_MAX30102_WRIST_IRAC_THR
#endif

#ifndef BPMWATCH_MAX30102_WRIST_MIN_IR_AC_RATIO_PPM
#define BPMWATCH_MAX30102_WRIST_MIN_IR_AC_RATIO_PPM \
  BPMWATCH_MAX30102_WRIST_RATIO_THR_PPM
#endif

#ifndef BPMWATCH_MAX30102_BPM_MIN
#define BPMWATCH_MAX30102_BPM_MIN 45
#endif

#ifndef BPMWATCH_MAX30102_BPM_MAX
#define BPMWATCH_MAX30102_BPM_MAX 180
#endif

#ifndef BPMWATCH_MAX30102_WRIST_MODE
#define BPMWATCH_MAX30102_WRIST_MODE true
#endif

#ifndef BPMWATCH_MAX30102_REFRACTORY_MS
#define BPMWATCH_MAX30102_REFRACTORY_MS 350U
#endif

#ifndef BPMWATCH_MAX30102_INTERVAL_MIN_MS
#define BPMWATCH_MAX30102_INTERVAL_MIN_MS 400U
#endif

#ifndef BPMWATCH_MAX30102_INTERVAL_MAX_MS
#define BPMWATCH_MAX30102_INTERVAL_MAX_MS 1300U
#endif

#ifndef BPMWATCH_MAX30102_INTERVAL_JUMP_PERCENT
#define BPMWATCH_MAX30102_INTERVAL_JUMP_PERCENT 45U
#endif

#ifndef BPMWATCH_MAX30102_REQUIRED_STABLE_BEATS
#define BPMWATCH_MAX30102_REQUIRED_STABLE_BEATS 3U
#endif

#ifndef BPMWATCH_MAX30102_RESET_ON_NO_FINGER
#define BPMWATCH_MAX30102_RESET_ON_NO_FINGER true
#endif

#ifndef BPMWATCH_MAX30102_MAX_INTERVAL_JUMP_PERCENT
#define BPMWATCH_MAX30102_MAX_INTERVAL_JUMP_PERCENT \
  BPMWATCH_MAX30102_INTERVAL_JUMP_PERCENT
#endif

#ifndef BPMWATCH_ENABLE_I2C_SCAN
#define BPMWATCH_ENABLE_I2C_SCAN true
#endif

#ifndef BPMWATCH_ENABLE_SOS
#define BPMWATCH_ENABLE_SOS true
#endif

#ifndef BPMWATCH_ENABLE_RADAR_HEADING
#define BPMWATCH_ENABLE_RADAR_HEADING true
#endif

#define BPMWATCH_NEEDS_I2C \
  (BPMWATCH_ENABLE_I2C_SCAN || BPMWATCH_ENABLE_COMPASS || BPMWATCH_ENABLE_MAX30102)
