#pragma once

#ifndef BPMWATCH_ENABLE_DISPLAY
#define BPMWATCH_ENABLE_DISPLAY true
#endif

#ifndef BPMWATCH_ENABLE_GY511
#define BPMWATCH_ENABLE_GY511 true
#endif

#ifndef BPMWATCH_ENABLE_COMPASS
#define BPMWATCH_ENABLE_COMPASS BPMWATCH_ENABLE_GY511
#endif

#ifndef BPMWATCH_ENABLE_LSM303D
#define BPMWATCH_ENABLE_LSM303D BPMWATCH_ENABLE_COMPASS
#endif

#ifndef BPMWATCH_ENABLE_COMPASS_DIAG
#define BPMWATCH_ENABLE_COMPASS_DIAG BPMWATCH_ENABLE_COMPASS
#endif

#ifndef BPMWATCH_ENABLE_COMPASS_ACC_RAW
#define BPMWATCH_ENABLE_COMPASS_ACC_RAW BPMWATCH_ENABLE_COMPASS
#endif

#ifndef BPMWATCH_ENABLE_TILT_COMPENSATION
#define BPMWATCH_ENABLE_TILT_COMPENSATION false
#endif

#ifndef BPMWATCH_ENABLE_MAX30102
#define BPMWATCH_ENABLE_MAX30102 true
#endif

#ifndef BPMWATCH_ENABLE_I2C_SCAN
#define BPMWATCH_ENABLE_I2C_SCAN true
#endif

#ifndef BPMWATCH_ENABLE_SOS
#define BPMWATCH_ENABLE_SOS true
#endif

#ifndef BPMWATCH_ENABLE_RADAR_HEADING
#define BPMWATCH_ENABLE_RADAR_HEADING true
#endif

#define BPMWATCH_NEEDS_I2C \
  (BPMWATCH_ENABLE_I2C_SCAN || BPMWATCH_ENABLE_COMPASS || BPMWATCH_ENABLE_MAX30102)
