[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
  -D BPMWATCH_SLAVE=1
  -D BPMWATCH_NODE_ID=1
lib_extra_dirs =
  ../../lib
lib_deps =
  adafruit/Adafruit GFX Library
  adafruit/Adafruit ST7735 and ST7789 Library
