[env:wokwi-esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
  -D BPMWATCH_WOKWI_SIM=1
  -I ../../master/src
lib_deps =
  adafruit/Adafruit GFX Library
  adafruit/Adafruit ILI9341
